query GET_USER {
  user {
    id
    username
  }
}

query GET_USERS {
  users {
    id
    username
  }
}

query GET_POST {
  post {
    id
    title
  }
}

query GET_POSTS {
  posts {
    id
    title
  }
}
